[workspace]
resolver = "3"
members = [
    "doss/rust-lib", 
    "streamablejson/rust-lib",
    #"pg-doss/extension",
    "shoutout"
    , "commons/rust-lib", "elbow/rust-lib", "streamablejson/rust-macros"]
